<h1>Login</h1>

<form method="POST" action="">
  Email: <input type="text" name="user"><br>
  Senha: <input type="password" name="pass"><br>
  <input type="submit" value="Entrar">
</form>

<?php
if(empty($_SESSION['userlogin']) && !empty($_POST))
	$this->login(filter_input_array(INPUT_POST));
elseif(!empty($_SESSION['userlogin']) && $_SESSION['userlogin']['user_level'] >= 3)
	header("Location: /admin/dash");
?>